### ISSUE TITLE
Organizer Sign-up

### ISSUE THREAD

**Issue by Hamorim85** [codefordenver/encorelink#44] opened 2016-07-26 17:06 UTC

**Comment by darrenrichmond** [comment] 2016-07-27 04:10
I think this is a duplicate of 46 Organizer Registers. OK to delete?

**Comment by Hamorim85** [comment] 2016-07-27 16:17
Yes

**Comment by darrenrichmond** [comment] 2016-07-27 16:24
Deleting as duplicate of 46.

**Closed as completed** 2016-07-27 16:24 UTC
