### ISSUE TITLE
Musician Get to Registration

### ISSUE THREAD

**Issue by Shuzy** [codefordenver/encorelink#55] opened 2016-07-26 18:14 UTC

**Comment by darrenrichmond** [comment] 2016-07-27 03:37
I'm ranking this super high because we can use the email campaign with a simple landing page that says "Thanks for your interest! We'll contact you when we're ready!" - that will allow us to track how many musicians are interested enough in our product to initiate registration.

**Comment by darrenrichmond** [comment] 2016-08-18 02:28
Closing as duplicate of 45, now that this encompases both Organizer an Volunteer roles.

**Closed as completed** 2016-08-18 02:28 UTC
Labels: duplicate
