### ISSUE TITLE
Dupe: Add initial simple form for creating a new event

### ISSUE THREAD

**Issue by wdoug** [codefordenver/encorelink#85] opened 2016-08-16 02:17 UTC
Probably just need `name` and `date` / `time` fields

**Comment by wdoug** [comment] 2016-08-16 02:19
Can reference login / register components

**Comment by darrenrichmond** [comment] 2016-08-24 01:24
Closing as duplicate of

**Closed as completed** 2016-08-24 01:23 UTC
Labels: duplicate

**Comment by darrenrichmond** [comment] 2016-08-24 01:25
Closing as duplicate of #98, which already has pull request.
