### ISSUE TITLE
Registration: Skin

### ISSUE THREAD

**Issue by Hamorim85** [codefordenver/encorelink#46] opened 2016-07-26 17:07 UTC
Signup has moved to the Home page:
![image](https://cloud.githubusercontent.com/assets/18622286/17915833/1f2f79ee-696b-11e6-9eb2-2b4066504fe1.png)

**Comment by Hamorim85** [comment] 2016-07-27 16:19
Few things Julia had written down for this page:

After you sign up for an account, please make sure you complete your profile for us to review the organization membership. After 1-2 days, you will receive an email from us to confirm your organization registration and then you will be able to schedule music performances!

Username:_____________
Password:______________
Confirm Password:_______

[Create account]

Please complete your profile: 
Organization Name:_____________________ 
Your name:_____________
Job title:________________
Address:________________
City:______________
State:____________ Zipcode:_____________
Email:__________________
Phone:______________ Ext:____________
Best Contact ways/time: ________________
Special notes (about the facility) 
(Text box)

Please read the disclaimer here. By signing up you agree to this agreement. 
[ ] Yes, I agree

[ Sign up ]

**Comment by Hamorim85** [comment] 2016-07-27 16:20
The agreement for this sign up has to be written by a lawyer; if possible. Basically dissolving any responsible from the app.

**Comment by Hamorim85** [comment] 2016-07-27 16:21
Robot would send an email "Thank you for signing up, we will contact you soon."

**Comment by wdoug** [comment] 2016-08-16 03:47
Log in the user upon successful registration

**Comment by darrenrichmond** [comment] 2016-08-24 01:51
I think this is now a duplicate of 84, since we have moved signup to the Home page.

**Comment by wdoug** [comment] 2016-08-26 06:03
#110 implements the last point about logging in on successful creation

**Closed as completed** 2016-09-13 01:02 UTC
Labels: Frontend
