### ISSUE TITLE
Musician Confirmation Email

### ISSUE THREAD

**Issue by Shuzy** [codefordenver/encorelink#61] opened 2016-07-26 18:28 UTC
As a Volunteer, I want to receive a confirmation (email by default) that summarize the location, time and special notes for the upcoming event that I signed up for, and was just approved by the Organizer.

**Comment by darrenrichmond** [comment] 2016-08-19 03:53
Closing as duplicate of 38

**Closed as completed** 2016-08-19 03:53 UTC
Labels: duplicate
